baseURL = "https://uapi-group.org/kernel-features"
languageCode = "en-us"
title = "UAPI Group Kernel Feature Ideas"
theme = "hugo-book"

[[menu.before]]
  name = "⬅️  Back to top"
  url = "https://uapi-group.org/"
  weight = 1
[[menu.before]]
  name = "⸻"
  weight = 2

# Uncomment to show second separator after more content files were added
#
#[[menu.after]]
#  name = "⸻"
#  weight = 10

[[menu.after]]
  name = "Collaborate on Github"
  url = "https://github.com/uapi-group/kernel-features"
  weight = 11

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  BookPortableLinks = true
  BookRepo = 'https://github.com/uapi-group/kernel-features'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main'
  BookIndexPage = 'README.md'
